// <auto-generated />
namespace WebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class SixthMigr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SixthMigr));
        
        string IMigrationMetadata.Id
        {
            get { return "201712181257455_SixthMigr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
